/** Balance data: original prototype values. Both browser and server import this file. */
export const VERSION = '29.0.0';
export const MAX_DECK = 8;
export const ARENA = Object.freeze({
  width:720, height:1040, riverTop:482, riverBottom:558, bridges:[190,530],
  bridgeHalf:42, deployBottom:550, deployTop:490, advancedDeployInset:120, advancedCenterHalf:40, maxUnits:120,
  duration:180, overtime:60, maxEnergy:10, tick:0.1
});
export const SUMMON_DELAY_BY_COST = Object.freeze({1:.4,2:.5,3:.7,4:.9,5:1.2,6:1.5,7:1.8,8:2.1});
export function summonDelayFor(data){
  if(!data||data.spell||data.hidden||data.tunnelAnywhere)return 0;
  if(Number.isFinite(data.summonDelay))return Math.max(0,data.summonDelay);
  return SUMMON_DELAY_BY_COST[data.cost]??Math.max(.4,Math.min(2.5,.3+(data.cost||1)*.25));
}
export const UNITS = Object.freeze({
  blade: {id:'blade',mass:2,name:'アッシュ剣士',short:'剣士',role:'近接アタッカー',cost:2,hp:780,damage:112,speed:50,range:34,cooldown:1.05,radius:16,count:1,air:false,targetsAir:false,color:'#efc577',desc:'攻守の基準になる剣士。盾役の後ろで前線を押し上げる。'},
  knight:{id:'knight',mass:6,name:'アイアン衛士',short:'衛士',role:'近接タンク',cost:3,hp:1850,damage:202,speed:32,range:36,cooldown:1.35,radius:23,count:1,air:false,targetsAir:false,color:'#a7b9c3',desc:'高い体力で攻撃を受け止めながら、202の近接攻撃で前線を押し返す3コスト前衛。後ろに弓兵や術師を重ねると安定する。'},
  archer:{id:'archer',mass:1.2,name:'リーフ弓兵',short:'弓兵',role:'遠距離・対空・2体編成',cost:3,hp:304,damage:112,speed:45,range:165,cooldown:1.15,radius:12,count:2,air:false,targetsAir:true,projectile:'arrow',color:'#a6ca8b',desc:'小柄なリーフ弓兵2体を横並びで展開する3コスト遠距離カード。1体HP304・攻撃112・射程165で地上と空中を狙う。2体同時の射撃性能に合わせてコストを3へ調整。'},
  mage:{id:'mage',mass:1.6,name:'ルーン術師',short:'術師',role:'範囲攻撃・対空',cost:3,hp:480,damage:105,speed:39,range:158,cooldown:1.5,radius:15,count:1,air:false,targetsAir:true,projectile:'orb',splash:54,color:'#b9a0ef',desc:'3コストへ軽量化された範囲術師。魔力弾が周囲にもダメージを与え、密集した敵やコウモリに有効。'},
  spear:{id:'spear',mass:1.2,name:'スパーク槍兵',short:'槍兵',role:'中距離・低コスト',cost:2,hp:410,damage:82,speed:57,range:68,cooldown:0.9,radius:14,count:1,air:false,targetsAir:false,color:'#f6a98d',desc:'長い槍で剣士より少し離れて攻撃。素早い援軍や防衛に。'},
  bat:{id:'bat',mass:0.6,name:'コウモリの群れ',short:'コウモリ',role:'飛行・5体編成',cost:2,hp:92,damage:82,speed:74,range:28,cooldown:1.2,radius:11,count:5,air:true,targetsAir:true,color:'#b7a7dc',desc:'5体のコウモリがまとまって出撃し、川を飛び越える。1体HP92・攻撃82・攻撃間隔1.2秒。単体は脆いが、対空できない敵を数で一気に削る。'},
  bomber:{id:'bomber',mass:2,name:'ボンバー',short:'ボンバー',role:'地上範囲攻撃・山なり投擲',cost:2,hp:470,damage:174,speed:38,range:145,cooldown:1.8,radius:16,count:1,air:false,targetsAir:false,projectile:'bomb',splash:66,color:'#edaa66',desc:'2コストの範囲爆撃兵。爆弾を山なりに投げ、地上の密集へ174ダメージを与える。爆弾は以前より少しゆっくり飛ぶため、着弾までわずかな間がある。空中の敵には攻撃できない。'},
  cannon:{id:'cannon',mass:1000000,name:'大砲',short:'大砲',role:'防衛建物・耐久減衰',cost:3,hp:1000,damage:200,speed:0,range:218,cooldown:1,radius:24,count:1,air:false,targetsAir:false,projectile:'shell',building:true,decayPerSecond:30,color:'#8dbfb3',desc:'動かない3コスト防衛建物。HP1000・攻撃200・攻撃間隔1.0秒。設置後は毎秒30ずつ耐久が自然減少し、攻撃を受けなくても約33秒で崩れる。'},
  golem:{id:'golem',mass:16,name:'ストーンゴーレム',short:'ゴーレム',role:'建物特攻・超耐久分裂',cost:8,hp:4256,damage:260,speed:19,summonDelay:2.5,range:42,cooldown:2.5,radius:30,count:1,air:false,targetsAir:false,buildingOnly:true,deathDamage:260,deathRadius:75,splitType:'mini_golem',splitCount:2,color:'#8ea37d',desc:'建物だけを狙う超重量ゴーレム。HP4256・攻撃260で、2.5秒ごとに重い一撃を放つ。配置後は2.5秒かけて召喚され、倒されるとちびゴーレム2体へ分裂し、死亡時に周囲へ260ダメージ。'},
  berserker:{id:'berserker',mass:8.2,name:'クラッグバーサーカー',short:'クラッグ',role:'重量アタッカー・超高火力',cost:7,hp:3760,damage:842,speed:28,range:40,cooldown:1.8,radius:24,count:1,air:false,targetsAir:false,color:'#b96550',desc:'巨大な戦槌を振るう7コスト重量級アタッカー。HP3760・攻撃842・攻撃間隔1.8秒で、遅い代わりに正面からの殴り合いを強く押し切る。'},
  miniberserker:{id:'miniberserker',mass:4.3,name:'ミニバーサーカー',short:'ミニバサ',role:'近接・高速超火力',cost:4,hp:1390,damage:755,speed:46,range:34,cooldown:1.6,radius:18,count:1,air:false,targetsAir:false,color:'#c66a58',desc:'頭と体がほぼ1:1の小型バーサーカー。大剣を頭上に掲げてやや速く進み、HP1390・攻撃755の強烈な一撃を1.6秒間隔で叩き込む4コスト単体アタッカー。'},
  megaknight:{id:'megaknight',mass:11.5,name:'メガナイト',short:'メガナイト',role:'範囲近接・落下召喚・ジャンプ',cost:7,hp:3993,damage:263,speed:36,summonDelay:1.5,range:40,cooldown:1.6,radius:28,count:1,air:false,targetsAir:false,meleeSplash:48,megaKnight:true,dropDamage:420,dropRadius:48,jumpWindup:2,jumpMinRange:80,jumpMaxRange:160,jumpTravelTime:1.5,jumpDamage:537,jumpRadius:48,color:'#555d66',desc:'両手に黒い鉄球を持つ大型重戦士。HP3993・通常攻撃263。指定地点へ1.5秒後に上空から落下し、半径48へ420ダメージ。80～160の敵には2秒その場で溜め、1.5秒かけて大きく弧を描いてジャンプし、着地時は半径48へ537ダメージ。'},
  ironeye:{id:'ironeye',mass:1.55,name:'鉄の目',short:'鉄の目',role:'中距離・弱点マーク・一度きり回転突進',cost:4,hp:750,damage:125,speed:40,range:160,cooldown:1.3,radius:15,count:1,air:false,targetsAir:true,projectile:'iron_arrow',ironMark:true,markDamageBonus:.20,markThreshold:500,markBurstDamage:300,ironSpinOnce:true,spinTriggerRange:78,spinDistance:120,spinDuration:.4,spinDamage:180,spinHitRadius:22,spinSlowMove:.70,spinSlowDuration:2.5,color:'#547a58',desc:'顔を深いフードで隠した4コストの中距離暗殺弓兵。矢で敵ユニットへ鉄の目マークを付け、マーク中は味方から受けるダメージが20%増加。実ダメージが累計500に達すると印が砕けて追加300ダメージ。敵地上兵が近づくと1体につき一度だけ隠し刃で120ほど貫通突進し、命中した全員へ180ダメージ・マーク・2.5秒間30%鈍足を与える。'},
  tracker:{id:'tracker',mass:5.4,name:'追跡者',short:'追跡者',role:'近接・万能フック',cost:6,hp:1900,damage:220,speed:40,range:36,cooldown:1.4,radius:20,count:1,air:false,targetsAir:false,tracker:true,hookRange:180,hookMinRange:55,hookWindup:.6,hookPullDuration:.45,hookCooldown:4,hookAirAttackDuration:2,color:'#6b7479',desc:'顔の見えない細身の長身鎧騎士。右手に片手剣、左手に小盾を持つ。4秒ごとに射程180のフックを使用し、地上敵は自分の近接距離まで引き寄せる。空中敵も引き寄せられ、その対象だけ2秒間攻撃可能。建物へ刺した場合は建物を動かさず、自分が近接位置まで引き寄せられる。'},
  valkyrie:{id:'valkyrie',mass:4.8,name:'ヴァルキリー',short:'ヴァルキリー',role:'地上範囲・回転斬り',cost:4,hp:2200,damage:260,speed:34,range:34,cooldown:1.45,radius:20,count:1,air:false,targetsAir:false,meleeSplash:50,valkyrieSpin:true,color:'#d87947',desc:'オレンジの短髪と大きな斧が目印の4コスト地上戦士。HP2200・攻撃260。攻撃時は体を横倒しにせず、前向きと後ろ向きを切り替えながら斧だけを大きく振り回し、自分中心半径50の地上敵をまとめて薙ぎ払う。'},
  gargoyle:{id:'gargoyle',mass:.72,name:'ガーゴイル',short:'ガーゴイル',role:'飛行・高速3体編成',cost:3,hp:230,damage:102,speed:69,range:45,cooldown:1.15,radius:10,count:3,air:true,targetsAir:true,color:'#6968a5',desc:'青紫色の小型飛行魔獣3体を展開する3コストカード。1体HP230・攻撃102で、地上と空中の両方を狙える。移動は速く、ほぼ近接だが少しだけ離れた射程45から素早く襲いかかる。'},
  gargoyleswarm:{id:'gargoyleswarm',mass:.72,name:'ガーゴイルの群れ',short:'ガーゴイル群',role:'飛行・高速6体編成',cost:5,hp:230,damage:102,speed:69,range:45,cooldown:1.15,radius:10,count:6,air:true,targetsAir:true,spawnType:'gargoyle',color:'#7770b0',desc:'ガーゴイル6体を一気に展開する5コストの大群カード。1体ごとの性能は通常のガーゴイルと同じHP230・攻撃102・速度69・射程45。単体攻撃へ物量で押し切れる一方、範囲対空にはまとめて倒されやすい。'},
  mini_golem:{id:'mini_golem',hidden:true,mass:5.3,name:'ちびゴーレム',short:'ちび',role:'建物特攻・分裂後',cost:0,hp:851,damage:52,speed:25,range:32,cooldown:2.5,radius:18,count:1,air:false,targetsAir:false,buildingOnly:true,deathDamage:52,deathRadius:45,color:'#9aa88a',desc:'ストーンゴーレムが倒れた後に2体現れる小型体。本体のおよそ1/5となるHP851・攻撃52・死亡爆発52を持ち、攻撃間隔は本体と同じ2.5秒。'},
  boar:{id:'boar',mass:9.5,name:'アイアンボア',short:'ボア',role:'建物突撃・川越えチャージ',cost:4,hp:1696,damage:318,speed:69,range:28,cooldown:1.6,radius:18,count:1,air:false,targetsAir:false,buildingOnly:true,chargeDistance:105,chargeMultiplier:2.25,shovePower:14,shoveMassLimit:2.2,shoveCompression:.62,riverJumper:true,riverJumpTrigger:150,riverJumpTravelTime:.85,riverJumpLift:52,color:'#b4785f',desc:'HP1696・攻撃318・攻撃間隔1.6秒の建物特攻。川の近くでは橋へ迂回せず、その場から対岸へ直接ジャンプして進軍する。軽量な地上兵を押しのけ、105px走ると最初の体当たりが2.25倍。'},
  tigger:{id:'tigger',mass:1.8,name:'穴掘りティガー',short:'ティガー',role:'奇襲・対ユニット高火力',cost:3,hp:1100,damage:120,structureDamage:70,speed:50,range:30,cooldown:1.1,radius:16,count:1,air:false,targetsAir:false,tunnelAnywhere:true,burrowMin:.9,burrowMax:2.8,burrowBase:.55,burrowSpeedDivisor:380,color:'#c08a52',desc:'戦場の好きな地上地点へ地下移動する奇襲兵。地上に出た後は敵ユニットへ120ダメージ、タワー・設置物には70ダメージ。攻撃間隔1.1秒。潜行中は完全に攻撃対象外。'},
  muddragon:{id:'muddragon',mass:4.8,name:'マッドドラゴン',short:'泥竜',role:'空中範囲・泥沼制圧',cost:5,hp:1600,damage:200,speed:33,range:78,cooldown:1.6,radius:22,count:1,air:true,targetsAir:true,projectile:'mud',splash:45,mudRadius:45,mudDuration:2,mudTickEvery:.5,mudDamage:30,mudSlow:.70,color:'#8b7657',desc:'少し遅い飛行ドラゴン。射程78・半径45の範囲攻撃と2秒間の泥沼を持つが、v16でHPを2000から1600へ低下。泥沼は地上兵だけに30ダメージの継続攻撃と30%移動低下を与える。'},
  nightshade:{id:'nightshade',mass:1.05,name:'ナイトシェイド',short:'シェイド',role:'暗殺・無敵突進',cost:3,hp:520,damage:228,speed:79,range:30,cooldown:.82,radius:13,count:1,air:false,targetsAir:false,aggroRange:105,dashAggroRange:105,dashWindup:.6,dashMinRange:80,dashMaxRange:205,dashSpeed:650,dashMultiplier:2,dashCooldown:4,color:'#6f668f',desc:'近づいた敵や建物を捉えると0.6秒溜め、影の突進を行う。突進中は無敵で、到達時に通常の2倍ダメージ。その後は通常攻撃し、突進は4秒で再使用できる。'},
  mossling:{id:'mossling',mass:.45,name:'ゴブリン部隊',short:'ゴブ部隊',role:'混成群体・地上3＋槍2',cost:3,hp:155,damage:65,speed:64,range:21,cooldown:.8,radius:9,count:5,air:false,targetsAir:true,spawnTypes:['goblin_melee','goblin_melee','goblin_melee','goblin_spear','goblin_spear'],color:'#8fb56b',desc:'前衛ゴブリン3体と槍兵2体の混成部隊。前衛は攻撃65で地上のみ、槍兵は旧モスリング相当のHP155・攻撃45を維持し、地上と空中の両方を攻撃できる。'},
  goblin_melee:{id:'goblin_melee',hidden:true,mass:.45,name:'ゴブリン',short:'ゴブリン',role:'地上前衛',cost:0,hp:155,damage:65,speed:64,range:21,cooldown:.8,radius:9,count:1,air:false,targetsAir:false,color:'#8fb56b',desc:'ゴブリン部隊の地上前衛。旧モスリングより攻撃力が高い。'},
  goblin_spear:{id:'goblin_spear',hidden:true,mass:.45,name:'ゴブリン槍兵',short:'槍ゴブ',role:'遠距離投げ槍・対空',cost:0,hp:155,damage:45,speed:64,range:160,cooldown:.8,radius:9,count:1,air:false,targetsAir:true,projectile:'thrown_spear',color:'#9ebd72',desc:'ゴブリン部隊の後衛槍兵。槍を投げて射程160から地上・空中の両方を攻撃する。リーフ弓兵の射程165よりわずかに短く、マッドドラゴンより長い射程を持つ。'},
  skeleton:{id:'skeleton',mass:.20,name:'スケルトン',short:'スケルトン',role:'低コスト・3体編成',cost:1,hp:81,damage:81,speed:69,range:19,cooldown:.72,radius:7,count:3,air:false,targetsAir:false,color:'#d9d2b5',desc:'1コストでHP81・攻撃81のスケルトンを3体展開する低コスト群体。単体攻撃の足止めや素早い防衛に向く。'},
  boneswarm:{id:'boneswarm',mass:.20,name:'スケルトン部隊',short:'スケ部隊',role:'群体・15体編成',cost:4,hp:81,damage:81,speed:69,range:19,cooldown:.72,radius:7,count:15,air:false,targetsAir:false,spawnType:'skeleton',color:'#d9d2b5',desc:'HP81・攻撃81のスケルトン15体を一気に展開する超群体。単体攻撃へ圧倒的な物量で押し寄せる一方、範囲攻撃には弱い。'},
  tombstone:{id:'tombstone',mass:1000000,name:'墓石',short:'墓石',role:'設置物・スケルトン継続召喚',cost:3,hp:530,damage:0,speed:0,range:0,cooldown:99,radius:22,count:1,air:false,targetsAir:false,building:true,decayPerSecond:30,summonType:'skeleton',summonCount:2,summonInterval:4,summonOnDeploy:true,deathSummonType:'skeleton',deathSummonCount:4,color:'#7e8073',desc:'HP530の3コスト設置物。建設完了時にスケルトン2体を呼び、その後4秒ごとに2体を追加召喚。毎秒30ずつHPが自然減少し、破壊された瞬間は召喚待ちなしでスケルトン4体をその場に出す。'},
  elixirgolem:{id:'elixirgolem',mass:6.2,name:'エリクサーゴーレム',short:'エリゴレ',role:'建物特攻・2段階分裂・敵エリクサー付与',cost:3,hp:1568,damage:254,speed:30,range:34,cooldown:2,radius:23,count:1,air:false,targetsAir:false,buildingOnly:true,splitType:'elixir_golem_mid',splitCount:2,enemyEnergyOnDeath:1,elixirStage:1,color:'#e88ac5',desc:'3コストのピンク色の攻城ゴーレム。HP1568・攻撃254・攻撃間隔2秒で建物だけを狙う。倒されるとHP784・攻撃127の中型2体へ分裂し、さらに各中型がHP392・攻撃64の小型2体へ分裂する。撃破されるたび相手へエリクサーを与えるため、低コスト高耐久の代わりに処理後の反撃を招きやすい。'},
  elixir_golem_mid:{id:'elixir_golem_mid',hidden:true,mass:3.1,name:'エリクサーゴーレム中型',short:'エリゴレ中',role:'建物特攻・分裂中間体',cost:0,hp:784,damage:127,speed:30,range:30,cooldown:2,radius:16,count:1,air:false,targetsAir:false,buildingOnly:true,splitType:'elixir_blob',splitCount:2,enemyEnergyOnDeath:1,elixirStage:2,color:'#ed9ad0',desc:'エリクサーゴーレムが分裂した中型体。HP784・攻撃127で建物だけを狙い、倒されると小型2体へ分裂する。倒されるごとに相手へ1エリクサーを与える。'},
  elixir_blob:{id:'elixir_blob',hidden:true,mass:1.1,name:'エリクサーのしずく',short:'しずく',role:'建物特攻・最終分裂体',cost:0,hp:392,damage:64,speed:30,range:22,cooldown:2,radius:10,count:1,air:false,targetsAir:false,buildingOnly:true,enemyEnergyOnDeath:.5,elixirStage:3,color:'#f0a4d7',desc:'最終段階の丸いピンク色の小型体。HP392・攻撃64で建物だけを狙い、倒されるごとに相手へ0.5エリクサーを与える。'},
  royalgiant:{id:'royalgiant',mass:9.2,name:'ロイヤルジャイアント',short:'ロイジャイ',role:'遠距離・建物限定砲撃',cost:6,hp:3164,damage:307,speed:27,range:165,cooldown:1.8,radius:27,count:1,air:false,targetsAir:false,buildingOnly:true,projectile:'royal_shell',color:'#d8b16e',desc:'金髪と王冠が目印の大型砲兵。HP3164・攻撃307・攻撃間隔1.8秒。移動は遅いが、リーフ弓兵ほどの射程165から敵兵を無視して建物だけを大砲で砲撃する6コスト攻城ユニット。'},
  lumina:{id:'lumina',mass:2.2,name:'ヒーラー',short:'ヒーラー',role:'攻撃連動回復・前線支援',cost:4,hp:1900,damage:120,speed:39,range:120,cooldown:1.75,radius:17,count:1,air:false,targetsAir:false,projectile:'light',healOnHit:110,healOnHitRange:120,healOnHitMaxAllies:3,color:'#e7dba8',desc:'敵へ攻撃が命中するたびに自分を110回復し、さらに周囲120以内で傷ついた味方ユニットを最大3体まで各110回復する戦闘型ヒーラー。HP1900・攻撃120・攻撃間隔1.75秒で、攻撃できている間ほど前線を粘り強く支える。'},
  frost:{id:'frost',mass:1.5,name:'フロストシャーマン',short:'シャーマン',role:'範囲妨害・3段階鈍足',cost:3,hp:535,damage:74,speed:38,range:170,cooldown:1.4,radius:15,count:1,air:false,targetsAir:false,projectile:'frost',splash:38,slowMoveStages:[.80,.65,.50],slowAttackStages:[.90,.80,.70],slowDuration:3,color:'#9ccfe2',desc:'3コストの氷術師。半径38の氷弾で地上の敵をまとめて攻撃し、鈍足を3段階まで重複させる。効果中に再被弾するとLvが上がり、Lv1/2/3で移動速度が80%/65%/50%へ低下。命中のたびに3秒へ更新する。'},
  harpy:{id:'harpy',mass:1.05,name:'ストームハーピー',short:'ハーピー',role:'空中遠距離・減衰連鎖スタン',cost:4,hp:505,damage:180,speed:57,range:175,cooldown:2,radius:16,count:1,air:true,targetsAir:true,projectile:'lightning',chainCount:3,chainRange:105,chainDamages:[180,130,90],stunDuration:1,color:'#8fa9d8',desc:'2秒ごとに強力な連鎖雷を放つ。1体目180、2体目130、3体目90と連鎖するほどダメージが低下し、命中した各敵を1秒スタンしてザップと同じターゲット・特殊状態リセットを行う。'},
  electrowizard:{id:'electrowizard',mass:1.7,name:'エレキテルウィザード',short:'エレキテル',role:'長射程・範囲スタン',cost:4,hp:650,damage:135,speed:38,range:185,cooldown:2.4,radius:15,count:1,air:false,targetsAir:true,projectile:'electro',splash:35,stunDuration:1,stunUnitsOnly:true,color:'#76bcd5',desc:'地上・空中へ届く長射程の電撃術師。2.4秒ごとに135ダメージの狭い範囲雷を放ち、範囲内の敵ユニット全員を1秒スタンする。射程185でリーフ弓兵より長く、密集した部隊への妨害に強い。'},
  necromancer:{id:'necromancer',mass:2.1,name:'ネクロマンサー',short:'ネクロ',role:'範囲対空・スケルトン召喚',cost:5,hp:839,damage:125,speed:39,range:158,cooldown:1.1,radius:17,count:1,air:false,targetsAir:true,projectile:'necro',splash:45,summonType:'skeleton',summonCount:3,summonInterval:7.5,summonOnDeploy:true,color:'#8b79a8',desc:'5コストの範囲召喚士。HP839・攻撃125・攻撃間隔1.1秒。地上・空中へ届く半径45の範囲魔法を放ち、召喚完了時にスケルトン3体、その後7.5秒ごとに3体を追加召喚する。'},
  darknecro:{id:'darknecro',mass:2.0,name:'ダークネクロマンサー',short:'闇ネクロ',role:'地上近接・バット召喚',cost:4,hp:907,damage:304,speed:41,range:34,cooldown:1.3,radius:16,count:1,air:false,targetsAir:false,summonType:'bat',summonCount:2,summonInterval:6.5,summonOnDeploy:true,color:'#65577c',desc:'4コストの地上近接召喚士。HP907・攻撃304。召喚完了時にコウモリ2体を呼び、その後も6.5秒ごとに2体を追加召喚する。本体は空中を攻撃できない。'},
  dosranboss:{id:'dosranboss',mass:2.35,name:'ドスランボス',short:'ドスラン',role:'近接前衛・群れ召喚',cost:6,hp:1100,damage:170,speed:36,range:32,cooldown:1.45,radius:19,count:1,air:false,targetsAir:false,summonType:'ranbos',summonCount:3,summonInterval:10,summonWindup:3,summonOnDeploy:true,color:'#4c79a8',desc:'大型ラプトルの首領。移動速度は遅め。1.5秒の本体召喚が完了した瞬間にランボス3体を呼び、その後も10秒ごとに3秒足を止めてランボス3体を追加召喚する。'},
  ranbos:{id:'ranbos',mass:0.88,name:'ランボス',short:'ランボス',role:'召喚子分',cost:0,hp:360,damage:58,speed:66,range:22,cooldown:1.15,radius:11,count:1,air:false,targetsAir:false,hidden:true,color:'#6f9cc9',desc:'ドスランボスに付き従う小型ラプター。性能は本体のおよそ3分の1で、素早く噛みついて前線をかく乱する。'},
  ashsquad:{id:'ashsquad',mass:2,name:'アッシュ部隊',short:'アッシュ隊',role:'近接部隊・3体編成',cost:5,hp:780,damage:112,speed:50,range:34,cooldown:1.05,radius:16,count:3,air:false,targetsAir:false,spawnType:'blade',color:'#d8b56f',desc:'アッシュ剣士3体を一度に展開する部隊カード。敵方向へ1体を前、2体を後ろにした三角陣形で出現し、後衛ユニットへ重ねる防衛や一斉近接攻撃に向く。'},
  princess:{id:'princess',mass:1.1,name:'プリンセスアーチャー',short:'プリンセス',role:'超長射程・範囲対空',cost:3,hp:300,damage:275,speed:25,range:350,cooldown:3,radius:14,count:1,air:false,targetsAir:true,projectile:'royal_arrow',splash:70,color:'#e5b7c9',desc:'巨大な弓を扱う超長射程の範囲射手。橋を渡らず自陣側から敵サイドタワーを狙える射程350を持ち、地上・空中へ3秒ごとに275ダメージ。着弾地点の半径70にも攻撃が広がる。HP300と非常に脆く、矢の雨なら一撃で倒される。'},
  sparky:{id:'sparky',mass:8.8,name:'スパーキー',short:'スパーキー',role:'常時充電・超火力範囲',cost:6,hp:1500,damage:1200,speed:23,summonDelay:1.8,range:145,cooldown:0,radius:23,count:1,air:false,targetsAir:false,projectile:'sparkblast',splash:90,sparkUnit:true,sparkChargeTime:3.5,color:'#d8b45c',desc:'地上のみを狙う6コストの超火力兵器。1.8秒の召喚完了後から敵がいなくても3.5秒充電し、満充電なら敵が射程へ入った瞬間に1200の広範囲攻撃を放つ。発射後は再充電。ザップを受けると充電が0へ戻り、スタン解除後に最初から充電し直す。'},

  blowdart:{id:'blowdart',mass:.9,name:'吹き矢ゴブリン',short:'吹き矢',role:'長射程・高速対空',cost:3,hp:240,damage:110,speed:46,range:195,cooldown:.5,radius:12,count:1,air:false,targetsAir:true,projectile:'dart',color:'#8fbd63',desc:'HP240と非常に脆い代わりに、0.5秒ごとに110ダメージを放つ長射程射手。v16で射程を220から195へ短縮し、タワーの反撃が届かない位置から一方的に攻撃できないよう調整。地上・空中の両方に対応する。'},
  lasertower:{id:'lasertower',mass:1000000,name:'レーザー塔',short:'レーザー塔',role:'防衛建物・単体増幅レーザー',cost:5,hp:2000,damage:20,speed:0,range:220,cooldown:.1,radius:26,count:1,air:false,targetsAir:true,building:true,laserTower:true,laserBaseDps:20,laserRampEvery:1.5,laserMultiplier:2,color:'#9c8ed0',desc:'同じ敵へ照射し続けるほど1.5秒ごとに威力が倍化する5コスト防衛建物。初期火力はボーン1体すらすぐ倒せないほど低いが、上限はない。対象が死亡・射程外・攻撃対象外になると次の対象へ切り替わり、火力は初期値へ戻る。'},
  laserdragon:{id:'laserdragon',mass:4.2,name:'レーザードラゴン',short:'レーザー竜',role:'飛行・単体増幅レーザー',cost:5,hp:1300,damage:20,speed:41,range:145,cooldown:.1,radius:21,count:1,air:true,targetsAir:true,laserUnit:true,laserBaseDps:20,laserRampEvery:1.5,laserMultiplier:2,color:'#71a4d6',desc:'地上・空中の両方を狙える5コスト飛行ドラゴン。移動速度は標準、射程145の中距離。レーザー塔と同じく同じ敵へ照射し続けるほど1.5秒ごとに火力が倍化し、対象変更・射程外・スタンで増幅が初期値へ戻る。'},
  shieldknight:{id:'shieldknight',mass:6.5,name:'シールドナイト',short:'盾騎士',role:'正面防御・前衛タンク',cost:4,hp:1400,damage:110,speed:38,range:34,cooldown:1.2,radius:22,count:1,air:false,targetsAir:false,shieldMax:650,shieldAbsorb:.65,shieldArcDeg:120,color:'#8ea7b5',desc:'大盾で正面約120度からの通常攻撃を受け止める4コスト前衛。盾耐久650が残る間は正面ダメージの65%を盾が吸収し、35%だけ本体へ通す。横・背後からの攻撃やスペル・継続ダメージは盾を無視する。'},
  windmage:{id:'windmage',mass:1.55,name:'ウィンドメイジ',short:'風術師',role:'遠距離・ノックバック',cost:4,hp:570,damage:95,speed:39,range:175,cooldown:1.6,radius:15,count:1,air:false,targetsAir:true,projectile:'wind',knockback:true,color:'#8bc7b0',desc:'地上・空中へ風弾を放つ位置操作術師。命中した敵を攻撃方向へ押し戻し、軽量ほど大きく飛ばす。小型約34px・中型約20px・大型約8px、超重量と建物は動かせない。'},
  phoenix:{id:'phoenix',mass:2.1,name:'フェニックス',short:'フェニックス',role:'飛行・一度だけ復活',cost:5,hp:900,damage:130,speed:54,range:110,cooldown:1.2,radius:18,count:1,air:true,targetsAir:true,projectile:'phoenix_fire',phoenixRevive:true,eggType:'phoenix_egg',color:'#e57d4b',desc:'地上・空中へ炎を放つ飛行ユニット。最初に倒されると地上へHP600の卵を残し、4秒間壊されなければHP450で一度だけ復活する。川上で倒れた場合は最寄りの安全な地面へ卵が落ちる。'},
  phoenix_egg:{id:'phoenix_egg',hidden:true,mass:1000,name:'フェニックスの卵',short:'卵',role:'復活待機',cost:0,hp:600,damage:0,speed:0,range:0,cooldown:99,radius:16,count:1,air:false,targetsAir:false,eggUnit:true,eggHatchTime:4,hatchType:'phoenix',color:'#e6a65b',desc:'フェニックスが最初に倒された場所へ残る卵。4秒守り切るとフェニックスがHP50%で一度だけ復活する。'},
  gravityorb:{id:'gravityorb',mass:1.7,name:'グラビティオーブ',short:'重力球',role:'範囲吸引・位置操作',cost:4,hp:540,damage:60,speed:36,range:165,cooldown:2.2,radius:15,count:1,air:false,targetsAir:true,projectile:'gravity',splash:60,gravityPull:true,color:'#9b8bc8',desc:'重力弾の着弾点から半径60の敵へ60ダメージを与え、中心へ引き寄せる支援ユニット。軽量ほど強く吸い寄せ、大型への効果は小さく、建物は動かさない。'},
  mirage:{id:'mirage',mass:1.05,name:'ミラージュアサシン',short:'ミラージュ',role:'ステルス・後衛暗殺',cost:3,hp:500,damage:190,speed:74,range:28,cooldown:.9,radius:13,count:1,air:false,targetsAir:false,stealthDuration:3,stealthFirstMultiplier:1.4,color:'#7f79a8',desc:'召喚完了後に最大3秒ステルスし、敵ユニットとタワーから直接狙われず後衛へ接近する。初撃は1.4倍。攻撃・3秒経過・ダメージ被弾で姿を現し、範囲攻撃やスペルにはステルス中でも巻き込まれる。'},
  skybomber:{id:'skybomber',mass:2.4,name:'スカイボマー',short:'空爆兵',role:'飛行・全対象爆撃',cost:4,hp:650,damage:175,speed:51,range:75,cooldown:1.6,radius:17,count:1,air:true,targetsAir:true,projectile:'sky_bomb',color:'#7ba0ad',desc:'地上ユニット・空中ユニット・建物を狙える4コスト飛行爆撃兵。HP650、攻撃175、速度51、射程75、攻撃間隔1.6秒。近くの敵へ上空から爆弾を投下する。'},
  scrapdrill:{id:'scrapdrill',mass:3.4,name:'スクラップドリル',short:'ドリル',role:'建物特攻・張り付き増幅',cost:4,hp:900,damage:90,speed:46,range:24,cooldown:.1,radius:18,count:1,air:false,targetsAir:false,buildingOnly:true,drillUnit:true,drillBaseDps:90,drillRampEvery:1.5,drillDpsStages:[90,135,180,240],color:'#9b815d',desc:'建物へ張り付いてドリルを回し続ける4コスト特攻兵。接触直後90 DPSから始まり、1.5秒ごとに135→180→240 DPSへ上昇。建物から離される・対象変更・スタンで90 DPSへ戻る。'},
  crusherogre:{id:'crusherogre',mass:10.5,name:'クラッシャーオーガ',short:'オーガ',role:'建物特攻・超低速増幅打撃',cost:6,hp:2200,damage:230,speed:27,range:40,cooldown:3,radius:26,count:1,air:false,targetsAir:false,buildingOnly:true,crusherRamp:true,crusherDamages:[230,310,390,470],color:'#967257',desc:'建物だけを狙う6コスト重量級。攻撃間隔は非常に遅い3秒だが、同じ建物を殴るたび230→310→390→470へ一撃が強化される。対象変更・射程外・スタンで230へリセット。'},
  siegeturtle:{id:'siegeturtle',mass:12.5,name:'シージタートル',short:'攻城亀',role:'建物特攻・対射撃装甲・近接反撃',cost:5,hp:2050,damage:220,speed:21,range:38,cooldown:1.8,radius:27,count:1,air:false,targetsAir:false,buildingOnly:true,siegeTurtle:true,movingRangedReduction:.40,retaliationRatio:1/3,retaliationRadius:54,color:'#758c6d',desc:'甲羅にこもって建物へ進む5コスト重装特攻兵。移動中は通常の遠距離攻撃・タワー射撃・レーザーのダメージを40%軽減。さらに近接や接触でダメージを受けると、受けた実ダメージの1/3を周囲の敵ユニットへ返す。建物へ到着して攻撃中は甲羅を開くため軽減が消える。遠距離攻撃には反撃できず、スペル・継続ダメージも反撃しない。'},
  bombcarrier:{id:'bombcarrier',mass:1.3,name:'ボムキャリア',short:'爆弾運び',role:'建物特攻・高速自爆',cost:3,hp:430,damage:480,speed:79,range:18,cooldown:99,radius:13,count:1,air:false,targetsAir:false,buildingOnly:true,suicideUnit:true,suicideDamage:480,carrierDeathDamage:80,carrierDeathRadius:55,color:'#b98956',desc:'建物だけを狙って全速力で走る3コスト使い捨て特攻兵。建物へ到達すると自爆して480ダメージを与えて消滅。途中で倒されても周囲の敵ユニットへ80ダメージの小爆発を残す。'},
  fireball:{id:'fireball',cardType:'spell',spell:'fireball',name:'ファイヤーボール',short:'火球',role:'呪文・範囲爆撃',cost:4,damage:689,buildingDamage:159,radius:90,count:0,targetsAir:true,color:'#ed7a47',desc:'戦場の好きな場所へ本拠地から火球を放つ。半径90にユニット689ダメージ、建物159ダメージ。遠いほど着弾が遅く、追尾しないため偏差撃ちが必要。'},
  poison:{id:'poison',cardType:'spell',spell:'poison',name:'ポイズン',short:'ポイズン',role:'呪文・8秒継続毒エリア',cost:3,damage:91,buildingDamage:21,radius:90,count:0,targetsAir:true,zoneDuration:8,tickEvery:1,lingerDuration:0,lingerDamage:0,color:'#c94f5c',desc:'指定地点へ遅延なしで毒エリアを8秒展開。範囲内の敵ユニットへ毎秒91ダメージ、建物へ毎秒21ダメージ。範囲を離れた後の残留毒は発生しない。'},
  arrowrain:{id:'arrowrain',cardType:'spell',spell:'arrowrain',name:'矢の雨',short:'矢の雨',role:'呪文・広範囲一斉射撃',cost:3,damage:366,buildingDamage:75,radius:130,count:0,targetsAir:true,color:'#c89b68',desc:'ファイヤーボールより広い半径130へ矢を降らせる。ユニットへ366ダメージ、建物へ75ダメージ。着弾が速く、散らばった小型群体の緊急処理に向く。'},
  lightning:{id:'lightning',cardType:'spell',spell:'lightning',name:'ライトニング',short:'ライトニング',role:'呪文・高HP4体雷撃',cost:6,damage:1056,buildingDamage:265,radius:105,maxTargets:4,count:0,targetsAir:true,color:'#69aee8',desc:'半径105の範囲内にいる敵から現在HPが高い順に最大4体を選び、ユニットへ1056ダメージ、建物へ265ダメージの落雷を同時に与える6コスト呪文。'},
  zap:{id:'zap',cardType:'spell',spell:'zap',name:'ザップ',short:'ザップ',role:'呪文・瞬間スタン＋思考リセット',cost:2,damage:225,buildingDamage:225,radius:78,count:0,targetsAir:true,stunDuration:1.5,color:'#75bde8',desc:'指定地点へ瞬時に電撃を落とし、半径78の敵ユニット・建物へ225ダメージと1.5秒スタン。現在の攻撃対象を解除し、レーザー塔の火力上昇やスパーキーの充電も0へリセットする。スタン解除後に対象を選び直す。'},
  cyclone:{id:'cyclone',cardType:'spell',spell:'cyclone',name:'サイクロン',short:'サイクロン',role:'呪文・大範囲継続吸引',cost:3,damage:10,buildingDamage:0,radius:130,count:0,targetsAir:true,zoneDuration:3,pullSpeed:70,outerDps:10,midDps:20,innerDps:35,color:'#8bc8cf',desc:'指定地点に半径130の巨大な渦を3秒間生成。範囲内の敵ユニットを中心へ吸い寄せ続け、軽量ほど強く引き込む。建物・タワーは動かない。渦のダメージはおまけで、外周10・中間20・中心35 DPSと中心ほど少し痛い。吸引中も敵は攻撃・能力使用ができる。'}
});
export function cardDamageInfo(data){
  if(!data)return {unit:'-',tower:'-'};
  if(data.spell==='cyclone')return {unit:`${data.outerDps||0}〜${data.innerDps||0} DPS`,tower:'0'};
  if(data.spell==='poison')return {unit:`${data.damage} / ${data.tickEvery}秒`,tower:`${data.buildingDamage} / ${data.tickEvery}秒`};
  if(data.laserTower||data.laserUnit)return {unit:`${data.laserBaseDps||data.damage} DPS〜`,tower:`${data.laserBaseDps||data.damage} DPS〜`};
  if(data.drillUnit)return {unit:'攻撃不可',tower:`${(data.drillDpsStages||[data.damage]).join('→')} DPS`};
  if(data.crusherRamp)return {unit:'攻撃不可',tower:(data.crusherDamages||[data.damage]).join('→')};
  if(data.buildingOnly){
    let unit='攻撃不可';
    if(Number.isFinite(data.carrierDeathDamage))unit=`撃破時爆発 ${data.carrierDeathDamage}`;
    else if(Number.isFinite(data.deathDamage))unit=`死亡爆発 ${data.deathDamage}`;
    const tower=Number.isFinite(data.suicideDamage)?data.suicideDamage:(Number.isFinite(data.structureDamage)?data.structureDamage:data.damage);
    return {unit,tower:String(tower??0)};
  }
  const unit=Number.isFinite(data.damage)?data.damage:0;
  const tower=Number.isFinite(data.buildingDamage)?data.buildingDamage:(Number.isFinite(data.structureDamage)?data.structureDamage:unit);
  return {unit:String(unit),tower:String(tower)};
}
export const DECK = Object.freeze(Object.keys(UNITS).filter(id=>!UNITS[id].hidden));
export const UNIT_IDS = Object.freeze(DECK.filter(id=>!UNITS[id].spell));
export const SPELL_IDS = Object.freeze(DECK.filter(id=>!!UNITS[id].spell));
export const DEFAULT_DECK = Object.freeze(['knight','blowdart','archer','muddragon','dosranboss','arrowrain','lasertower','fireball']);
export const ROLE_ORDER = DECK;
export const TEAM_COLORS = ['#58b9ae','#ee9b81'];
export function normalizeDeck(value,{fallback=true}={}){
  const out=[];
  if(Array.isArray(value))for(const id of value){if(typeof id==='string'&&DECK.includes(id)&&!out.includes(id))out.push(id);if(out.length===MAX_DECK)break;}
  if(out.length===MAX_DECK)return out;
  return fallback?[...DEFAULT_DECK]:null;
}
